# Generated by Django 3.1.2 on 2020-11-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201102_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='a',
            new_name='Product_Title',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='imgDescription',
            new_name='image_Description',
        ),
    ]
