# Generated by Django 3.1.2 on 2020-11-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20201103_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
