# Generated by Django 3.1.2 on 2020-11-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20201104_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filters',
            field=models.CharField(choices=[('SmartPhone', 'SmartPhones'), ('Computer', 'Computer'), ('Laptop', 'Laptop'), ('Accessories', 'Accessories')], default='Computer', max_length=18),
        ),
    ]
