# Generated by Django 3.1.2 on 2020-11-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=models.CharField(choices=[('Smart', 'Smart'), ('Computer', 'Computer'), ('Laptop', 'Laptop'), ('Accessories', 'Accessories')], default='Computer', max_length=18),
        ),
    ]
