# Generated by Django 3.1.2 on 2020-11-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20201104_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='filters',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Smart', 'Smart'), ('Computer', 'Computer'), ('Laptop', 'Laptop'), ('Accessories', 'Accessories')], max_length=18),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
