# Generated by Django 3.1.2 on 2020-11-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='street',
            new_name='address',
        ),
    ]
