# Generated by Django 3.1.2 on 2020-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ccnum',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cvv',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expmonth',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expyear',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
