# Generated by Django 3.1.2 on 2020-11-20 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20201120_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='Shipping',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
