# Generated by Django 3.1.2 on 2020-11-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20201120_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Shipping',
            new_name='shipping',
        ),
    ]
